version: '3.8'
services:
  ollama:
    hostname: ollama-uploaded2
    container_name: ollama-uploaded2
    image: ollama/ollama
    ports:
      - "11434:11434"
    environment:
      - MODEL_NAME=mistral
    volumes:
      - ollama_models:/root/.ollama


  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=cvdocs'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'



volumes:
  ollama_models:
    external: true